
default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  username: geeksters 
  password: geeksters 

development:
  <<: *default
  database: my_database


test:
  <<: *default
  database: my_database_test

production:
  <<: *default
  database: my_database_prod